kind: Pod
apiVersion: v1
metadata:
  name: good-app
  labels:
    app: http-echo
spec:
  containers:
  - name: good-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=good"
---
kind: Pod
apiVersion: v1
metadata:
  name: great-app
  labels:
    app: http-echo
spec:
  containers:
  - name: great-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=great"
---
kind: Service
apiVersion: v1
metadata:
  name: good-service
spec:
  type: LoadBalancer
  selector:
    app: http-echo
  ports:
  # Default port used by the image
  - port: 5678